# Use official Tomcat with JDK 17
FROM tomcat:10.1-jdk17

# Remove default apps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy your WAR file to Tomcat as ROOT.war
COPY ROOT.war /usr/local/tomcat/webapps/ROOT.war

# Download and install MySQL JDBC driver
ADD https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.33/mysql-connector-java-8.0.33.jar /usr/local/tomcat/lib/

# Disable shutdown port (optional)
RUN sed -i 's/<Server port="8005"/<Server port="-1"/' /usr/local/tomcat/conf/server.xml

EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]
